### ISSUE TITLE
Code's no longer uploading to GitHub with consistency 

### ISSUE THREAD

**Issue by version0chiro** [QasimWani/LeetHub#106]
After multiple time the codes are uploaded and the amount of codes being uploaded just keeps on decreasing as the amount of code submitted increases. This may be a server overload or something, kindly fix this.

**Comment by QasimWani** [comment]
hmm, that's weird. how can I reproduce the bug?
You should ideally spend 2-3 seconds before u close leetcode or switch to another window. It might happen due to ur internet connection. Also, if ur submitting the same problem again w/o any changes, leethub will not push that commit. To push updated code, you NEED to reload leetcode and resubmit (and wait for couple of seconds, of course). 

lmk if ur still having any issues.
