### ISSUE TITLE
Authorization Security Issue

### ISSUE THREAD

**Issue by MrAsimZahid** [QasimWani/LeetHub#11]
Is it safe to give access and authorize "QasimWani" of our github?

![leethub](https://user-images.githubusercontent.com/23510373/100205386-dee8e600-2f26-11eb-878d-18d65ccc194c.png)

**Comment by QasimWani** [comment]
Hey there.
Yes it should be fine. Since I've open sourced everything, you're guaranteed knowledge of privacy and security of your data.
Note that ALL your data is stored locally on your browser (this is a client-side app, no server!). Since LeetHub needs permission to push files to your repository of choice, authenticating is a pre-requisite.
Note that over 120 users are already using this, making this top trending repository. So, you should be fine. Maybe someone else who's used it before can give their thoughts, since I might be a bit biased.
Good luck!
