### ISSUE TITLE
Unable to sync with Github

### ISSUE THREAD

**Issue by rohangawhade** [QasimWani/LeetHub#200]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
I re-installed Leethub but now it is not asking permission to sync with Github. Hence, it is unable to commit to my repository.
I had reset my chrome and re-installed Leethub but now it does not give any option to sync with Github.

**Expected behavior**
Able to see the authorize with Github option

**Screenshots**
![image](https://user-images.githubusercontent.com/49246157/150916921-73fbd74d-3736-4050-be80-04cbfb9e649c.png)

**Comment by QasimWani** [comment]
that's not how u uninstall leethub. see #188

**Comment by QasimWani** [comment]
If you followed the steps, you should not see any errors. Follow the steps in this [loom](https://www.loom.com/share/675ecae04beb409b8af75caa8245cf03). Instead of _Load Unpacked_, you'd reinstall it from the chrome webstore. 
Everything else should be the same. note that I'm using the leethub dev extension, hence the minor differences.

**Comment by rohangawhade** [comment]
Thank you. It worked now.
