### ISSUE TITLE
New Submissions Not Recommitting

### ISSUE THREAD

**Issue by JeremyTsaii** [QasimWani/LeetHub#24]
Seems like you have to navigate away from the problem then come back and resubmit before a submission is recommitted on GitHub. Is this on purpose?

**Comment by QasimWani** [comment]
so there's the setTimeOut that constantly looks for success and breaks if successful (committing after etc). I didn't want to recreate it because you can simply resubmit the problem without reloading it thereby exploding github commits which may not be an accurate representation. 
However, reloading the tab takes those commits away. It's not the best idea, but the new release does recommit existing files again. in reference to #18  (issue #1 )

**Comment by JeremyTsaii** [comment]
I see. What do you think about creating an on-click listener that runs the setTimeOut? This way it's only polling after a submission. I was thinking of doing something similar for the Discussion issue, so whenever a user clicks the Post button then we commit to README and add the post link.
