### ISSUE TITLE
Official solutions folder for premium users

### ISSUE THREAD

**Issue by thomaslam** [QasimWani/LeetHub#43]
Issue title is pretty self-explanatory but basically I just want official solutions available as a sub-folder of the problem folder with each solution having its own file. Would be great to have corresponding READMEs containing detailed explanations for official solutions but I'm fine with just copy pasting the code solutions

**Comment by QasimWani** [comment]
I don't have access to Leetcode premium so I can't design for the latter part of your question. The idea of having a solution as part of the folder submission seems interesting and I can work on that after my finals this week.

**Comment by thomaslam** [comment]
Ah gotcha. I guess you can add the top most voted submission in Discussion tab in the solution subfolder and adding a link to the post as a comment in the solution file would be good enough.

**Comment by QasimWani** [comment]
The point of leethub is to offer a lightweight portfolio. i can see the value your idea brings, but it'd increase network delay. LeetHub prefaces on optimization. Currently, all network requests take a max. of ~400ms. Increasing it can cause delays on clients' devices, especially since Leethub doesn't use a server to cache requests.
