### ISSUE TITLE
generate commit based on question difficulty

### ISSUE THREAD

**Issue by BRO3886** [QasimWani/LeetHub#52]
## Current: 
working commit - Created using LeetHub

## Suggestions:
easy - created using LeetHub
medium - created using LeetHub
hard - created using LeetHub

## Could be [gitmoji](https://gist.github.com/rxaviers/7360908) commits too:

:feelsgood: easy - created using LeetHub
:rage1: medium - created using LeetHub
:godmode:   hard - created using LeetHub

**Comment by QasimWani** [comment]
reload your chrome extension because v.0.1.0 displays performance stats on commits (see image below).
![image](https://user-images.githubusercontent.com/43754306/101907682-f6cd9480-3bcb-11eb-8122-d990cae01ca5.png)
Also, you can just look at the readme for difficulty level. 
Therefore, i don't find this issue meaningful.
