### ISSUE TITLE
Inconsistent commits

### ISSUE THREAD

**Issue by blazyy** [QasimWani/LeetHub#57]
Wonderful plugin- although I've noticed that it only pushes sometimes and mostly doesn't on submissions after the first initial successful submission. It'd be great if there was an option to enable or disable commits after the first initial commit. Personally, I improve my code after my initial solution, and I want the plugin to commit my improved code.

**Comment by QasimWani** [comment]
@blazyy, kindly refer to other issues before raising one! 
to be able to resubmit your code, you must:
1. Reload the page first and submit your code again (this is due to a timeout handler running in the background)
2. Make sure that the new submitted code is different from the prior version. This is because of the way commit hashes are used. If nothing is changed, the newer commit will be the same as the one prior.

Closing! Please re-open if it didn't solve your issue.
Thanks for using LeetHub
