### ISSUE TITLE
change naming scheme on github to include problem number

### ISSUE THREAD

**Issue by heidenrei** [QasimWani/LeetHub#58]
largest-rectangle-in-histogram -> 84_largest-rectangle-in-histogram

**Comment by QasimWani** [comment]
The readme has the problem number. Problem number in the directory seems unnecessary. Can you explain why this is a good idea, and why current implementation isn't sufficient?

**Comment by AmateurPirate** [comment]
It's a convenience thing, no more. The numbers serve as keys for lengthy values. If I want to search up a solution in my repo I would much rather search by problem number than problem name.

**Comment by trungnguyencs** [comment]
I would find this feature very useful if it's ever implemented. I have already solved a lot of problems on Leetcode before Leethub, and now I'm re-doing them so that they are pushed to my GitHub. 
However, without a problem number it's very difficult to keep track of which ones I have re-done and which ones haven't.

**Comment by QasimWani** [comment]
super busy with work. won't find a time to implement this feature. feel free to PR this change and i can review + merge it later!

**Comment by threemonks** [comment]
I would also like to have this problem number included in url as when I browse my github, it is much easier to find problem, and they are in some way sorted by problem number.
