### ISSUE TITLE
No option to auto save files in a subfolder inside repo

### ISSUE THREAD

**Issue by abhijatyagupta** [QasimWani/LeetHub#61]
Very useful extension Qasim! Another feature that'll be great to have is an option that let us set the autosave location as a subfolder inside an already existing repo, maybe something like typing [existing repo name] / [subfolder inside repo] in the repo name field on the welcome page.
If possible, an option to set custom commit summary and message would be great too.

**Comment by QasimWani** [comment]
hey, thanks for using leethub.
unfortunately, i'm no longer developing leethub. also, the more features we add, the slower the extension performs. since all runs locally, LeetHub operates at ~400ms, and we don't want to increase any latencies. so to comply with strict network requirements, we try to keep leethub very light-weighted.
that being said, your idea sounds interesting. as said before, i don't have the time to further develop the project. so, if you'd like to work on this idea, please open up a PR on dev branch and i'd be more than happy to merge it.
Qasim
